doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'App\Core\Infrastructure\Migrations': '%kernel.project_dir%/src/Core/Infrastructure/Migrations'
    enable_profiler: false
