twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['Twig/Theme/tailwind.html.twig']
    globals:
      app_name: '%env(resolve:APP_NAME)%'

when@test:
    twig:
        strict_variables: true
