twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['twig/theme/tailwind.html.twig']
    globals:
      app_name: '%env(resolve:APP_NAME)%'
      file_grave:
        images_directory: 'uploads/grave/images/'
        images_thumbnail_directory: 'uploads/grave/thumbs/'
when@test:
    twig:
        strict_variables: true
