grave_api_routes:
  prefix: '/api/admin'
  resource: 'grave'
  type: directory
  
person_api_routes:
  prefix: '/api/admin'
  resource: 'person'
  type: directory
  
payment_api_routes:
  prefix: '/api/admin'
  resource: 'payment'
  type: directory
  
file_api_routes:
  prefix: '/api/admin'
  resource: 'file'
  type: directory
