admin_web_grave_index:
  path: /admin/grave/page/{page}
  methods: [ GET, POST ]
  controller: App\Admin\UI\Web\Controller\Grave\GraveController::index
  defaults:
    page: 1
    
admin_web_grave_show:
  path: /admin/grave/show/{id}
  methods: [ GET, POST ]
  controller: App\Admin\UI\Web\Controller\Grave\GraveController::show
  options:
    expose: true
    
admin_web_grave_create:
  path: /admin/grave/create
  methods: [ GET, POST ]
  controller: App\Admin\UI\Web\Controller\Grave\GraveController::create
  
admin_web_grave_remove:
  path: /admin/grave/remove
  methods: [ GET, POST ]
  controller: App\Admin\UI\Web\Controller\Grave\GraveController::remove
