version: "3"

services:
  php-apache:
    container_name: "apache-${PROJECT_NAME}"
    restart: unless-stopped
    build: ./docker/php-apache
    tty: true
    volumes:
      - ${PATH_TO_SYMFONY_PROJECT}:/var/www/html
    ports:
      - "80:80"
  
  db:
    container_name: "mariadb-${PROJECT_NAME}"
    restart: unless-stopped
    image: mariadb:10.11.5
    environment:
      - MARIADB_ROOT_USER=${ROOT_USER}
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
    volumes:
      - ${PATH_TO_DB_DATA}:/var/lib/mysql:rw
    ports:
      - "3306:3306"
      
  node:
    container_name: "nodejs-${PROJECT_NAME}"
    restart: unless-stopped
    build: ./docker/node
    tty: true
    volumes:
      - ${PATH_TO_SYMFONY_PROJECT}:/var/www/html

###> symfony/mailer ###
  mailer:
    container_name: "mailcatcher-${PROJECT_NAME}"
    image: axllent/mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###
