grave_routes:
  resource: 'grave'
  type: directory
  
graveyard_routes:
  resource: 'graveyard'
  type: directory
  
person_routes:
  resource: 'person'
  type: directory
  
user_routes:
  resource: 'user'
  type: directory

