admin_web_user_list:
  path: /admin/manage/user/{page<\d+>}
  methods: [ GET ]
  controller: App\Admin\UI\Web\Controller\User\AdminController::list
  defaults:
    page: 1

admin_web_user_create:
  path: /admin/manage/user/create
  methods: [ GET, POST ]
  controller: App\Admin\UI\Web\Controller\User\AdminController::create
  defaults:
    priority: 2
