main_web:
  resource: 'routes/main/web/routes.yaml'

main_api:
  resource: 'routes/main/api/routes.yaml'
  
admin_web:
  resource: 'routes/admin/web/routes.yaml'

admin_api:
  resource: 'routes/admin/api/routes.yaml'

