main_web_frontpage_search:
  path: /main/frontpage/search/{page<\d+>}
  methods: [ GET, POST ]
  controller: App\Main\UI\Web\Controller\Frontpage\FrontpageController::search
  defaults:
    page: 1

main_web_frontpage_show:
  path: /main/frontpage/show/{id}
  methods: [ GET ]
  controller: App\Main\UI\Web\Controller\Frontpage\FrontpageController::show
  options:
    expose: true
